In [1]:
import numpy as np

In [2]:
myarr_1D = np.array([3,6,32,7])

In [3]:
print("1D array:", myarr_1D)

1D array: [ 3  6 32  7]


In [4]:
myarr_2D = np.array([[1,2,3],[4,5,6]])

In [6]:
print("2D array:", myarr_2D)

2D array: [[1 2 3]
 [4 5 6]]


## diffrence between array and lists

In [7]:
l1 = [1,2,3]
arr1 = np.array([1,2,3])

In [8]:
print("list multiplication:", l1*2)
print("array multiplication:", arr1*2)

list multiplication: [1, 2, 3, 1, 2, 3]
array multiplication: [2 4 6]


## Types of arrays

In [9]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
scalar_matrix = np.full((2,3),7)
print(scalar_matrix)

[[7 7 7]
 [7 7 7]]


In [12]:
random = np.random.random((2,3))
print(random)

[[0.40074793 0.25970045 0.92692785]
 [0.91674207 0.91319847 0.96659992]]


In [13]:
sequence = np.arange(0,10,2)
print(sequence)

[0 2 4 6 8]


## vector, matrix and tensor

In [16]:
vector = np.array([1,2,3])
print("vector:",vector)
matrix = np.array([[1,2,3],[4,5,6]])
print("matrix:", matrix)
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor:", tensor)

vector: [1 2 3]
matrix: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## array properties

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("dimension:", arr.ndim)
print("size:", arr.size)
print("Dtype:", arr.dtype)

shape: (2, 3)
dimension: 2
size: 6
Dtype: int64


## array reshaping

In [27]:
arr_1 = np.arange(12)
print("original array:" , arr_1)
reshaped = arr_1.reshape((3,4))
print("reshaped array:" , reshaped)
flattened = reshaped.flatten()
print("flattened array:" , flattened)
#ravel(return view, instead of copy)
reveled = reshaped.ravel()
print("reveled array:" , reveled)
transposed = reshaped.T
print("transposed array:" , transposed)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
