### numpy array operation

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing:", arr[2:7])
print("with steps:", arr[1:8:2])

basic slicing: [3 4 5 6 7]
with steps: [2 4 6 8]


In [8]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element:" , arr_2D[1,2])
print("entire row:", arr_2D[1])
print("entire column:", arr_2D[:,1])

specific element: 6
entire row: [4 5 6]
entire column: [2 5 8]


### sorting

In [13]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("sorted array:", np.sort(unsorted))
unsorted_2D = np.array([[3,1],[1,2],[2,3]])
print("sorted 2D by column:", np.sort(unsorted_2D, axis=0))
print("sorted 2D by raw:", np.sort(unsorted_2D, axis=1))

sorted array: [1 1 2 3 4 5 6 9]
sorted 2D by column: [[1 1]
 [2 2]
 [3 3]]
sorted 2D by raw: [[1 3]
 [1 2]
 [2 3]]


### array filtering

In [17]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = num[num%2 == 0]
print("even_numbers:", even_num)

even_numbers: [ 2  4  6  8 10]


### Filter with mask

In [19]:
mask = num>5
print("num greater then 5:", num[mask])

num greater then 5: [ 6  7  8  9 10]


### fancy indexing vs np.where()

In [22]:
indices = [0,2,4]
print(num[indices])

where_result = np.where(num>5)
print(where_result)
print("where array:", num[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
where array: [ 6  7  8  9 10]


In [26]:
conditional_array = np.where(num>5,num*2,num)
print(conditional_array)

[ 1  2  3  4  5 12 14 16 18 20]


### adding and removing data

In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### array compatiblity

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatiblity shape:", a.shape==b.shape)

compatiblity shape: True


In [18]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
w_new_row = np.vstack((original,new_row))
print(original)
print(w_new_row)

new_column = np.array([[7],[8]])
w_new_col = np.hstack((original,new_column))
print(w_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [21]:
arr_3 = np.array([1,2,3,4,5])
deleted = np.delete(arr_3,2)
print("array after deletion:", deleted)

array after deletion: [1 2 4 5]
